CREATE TABLE USERS
(
    ID           SERIAL PRIMARY KEY,
    LOGIN        VARCHAR(255) NOT NULL UNIQUE,
    ENC_PASSWORD BYTEA NOT NULL,
    SALT         BYTEA NOT NULL,
    ENABLED      BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE GROUPS
(
    ID          SERIAL PRIMARY KEY,
    NAME        VARCHAR(255) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(255) NOT NULL
);
CREATE TABLE ROLES
(
    ID          SERIAL PRIMARY KEY,
    NAME        VARCHAR(255) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(255)
);

CREATE TABLE GROUP_ROLES
(
    GROUP_ID INTEGER NOT NULL REFERENCES GROUPS (ID),
    ROLE_ID  INTEGER NOT NULL REFERENCES ROLES (ID),
    PRIMARY KEY (GROUP_ID, ROLE_ID)
);

CREATE TABLE USER_GROUPS
(
    USER_ID  INTEGER NOT NULL REFERENCES USERS (ID),
    GROUP_ID INTEGER NOT NULL REFERENCES GROUPS (ID),
    PRIMARY KEY (USER_ID, GROUP_ID)
);

