CREATE TABLE USER
(
    ID           SERIAL PRIMARY KEY,
    LOGIN        VARCHAR(255) NOT NULL,
    ENC_PASSWORD VARCHAR(255) NOT NULL,
    SALT         VARCHAR(255) NOT NULL,
    ENABLED      BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE GROUP
(
    ID          SERIAL PRIMARY KEY,
    NAME        VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL
);
CREATE TABLE ROLE (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(255),
    PARENT_ID INTEGER REFERENCES ROLES (ID)
);

CREATE TABLE GROUP_ROLE
(
    GROUP_ID INTEGER NOT NULL REFERENCES GROUPS (ID),
    ROLE_ID  INTEGER NOT NULL REFERENCES ROLES (ID),
    PRIMARY KEY (GROUP_ID, ROLE_ID)
);

CREATE TABLE USER_GROUP
(
    USER_ID  INTEGER NOT NULL REFERENCES USERS (ID),
    GROUP_ID INTEGER NOT NULL REFERENCES GROUPS (ID),
    PRIMARY KEY (USER_ID, GROUP_ID)
);

